### ISSUE TITLE
Are Diagonal Steps OK?

### ISSUE THREAD

**Issue by bkiu** [jacinator/CoordPy#1]
So here's a question: are diagonal steps OK? Is a step from `(1,1) -> (2,2)` a valid move? A call to `utils.get_all_steps((0,0), (3,3), method=utils.get_int_step)` yields the list `[(0.0, 0.0), (1, 1), (2, 2), (3, 3)]`. Technically, the step `(1,1) -> (2,2)` covers a distance of 1.4 and not 1. Maybe this is OK, and then no problem, but just wanted to see your thoughts.

This is what I was trying to figure out when I was working on pathing, and just want to see your ideas.

**Comment by jacinator** [comment]
Diagonal steps are fine. The default ``get_step`` returns floating points. With a one "mark" step being taken at a [45 degree angle the result is a hypotenuse of ~0.7](https://github.com/jacinator/CoordPy/blob/master/coordpy/tests.py#L167). When ``get_int_step`` is called it ``round``s the results from ``get_step``. Since that is the case the 0.7 is rounded up to 1 "mark" and the step is taken. Tests for ``get_int_step`` are found [here](https://github.com/jacinator/CoordPy/blob/master/coordpy/tests.py#L234). They don't cover a single step, but the ``get_step`` has that tested and it is mostly to test the rounding.
